### PR TITLE
Force use of system Eigen

### PR DESCRIPTION
**Pull request by eggerk**
With this change, swe works again.

### CODE REVIEW

**Comment by mfehr** [comment]
@eggerk have you tested this on 14.04?

**Comment by eggerk** [comment]
Yes, this should work with 14.04. I'll test all changes needed for new Eigen again to make sure

**Comment by eggerk** [comment]
SWE still working in 14.04

**Comment by hitimo** [comment]
```
catkin build gtsam_catkin
Found '122' packages in 0.1 seconds. 
Starting ==> catkin_simple                                                                                                                                                                                                           
Finished <== catkin_simple [ 0.2 seconds ]                                                                                                                                                                                           
Starting ==> eigen_catkin                                                                                                                                                                                                            
Finished <== eigen_catkin  [ 0.2 seconds ]                                                                                                                                                                                           
Starting ==> gtsam_catkin                                                                                                                                                                                                            
                                                                                                                                                                                                                                     
[gtsam_catkin] ==> 'build/gtsam_catkin/build_env.sh /usr/bin/make -j8 -l8' in build/gtsam_catkin'
[ 12%] Performing build step for 'gtsam_src'
make[3]: warning: jobserver unavailable: using -j1.  Add `+' to parent make rule.
[  1%] Built target CppUnitLite
[  7%] Built target wrap_lib
[  9%] Built target wrap
[ 30%] Built target metis
[ 30%] Building CXX object gtsam/CMakeFiles/gtsam.dir/nonlinear/LevenbergMarquardtOptimizer.cpp.o
In file included from /usr/include/eigen3/Eigen/src/Core/MatrixBase.h:139:0,
                 from /usr/include/eigen3/Eigen/Core:279,
                 from /usr/include/eigen3/Eigen/Dense:1,
                 from catkin_ws/build/gtsam_catkin/gtsam_src-prefix/src/gtsam_src/gtsam/base/OptionalJacobian.h:22,
                 from catkin_ws/build/gtsam_catkin/gtsam_src-prefix/src/gtsam_src/gtsam/base/Matrix.h:25,
                 from catkin_ws/build/gtsam_catkin/gtsam_src-prefix/src/gtsam_src/gtsam/base/Manifold.h:22,
                 from catkin_ws/build/gtsam_catkin/gtsam_src-prefix/src/gtsam_src/gtsam/base/Lie.h:25,
                 from catkin_ws/build/gtsam_catkin/gtsam_src-prefix/src/gtsam_src/gtsam/base/VectorSpace.h:11,
                 from catkin_ws/build/gtsam_catkin/gtsam_src-prefix/src/gtsam_src/gtsam/geometry/Point2.h:20,
                 from catkin_ws/build/gtsam_catkin/gtsam_src-prefix/src/gtsam_src/gtsam/nonlinear/NonlinearFactorGraph.h:24,
                 from catkin_ws/build/gtsam_catkin/gtsam_src-prefix/src/gtsam_src/gtsam/nonlinear/NonlinearOptimizer.h:21,
                 from catkin_ws/build/gtsam_catkin/gtsam_src-prefix/src/gtsam_src/gtsam/nonlinear/LevenbergMarquardtOptimizer.h:23,
                 from catkin_ws/build/gtsam_catkin/gtsam_src-prefix/src/gtsam_src/gtsam/nonlinear/LevenbergMarquardtOptimizer.cpp:21:
/usr/include/eigen3/Eigen/src/Core/../plugins/MatrixCwiseBinaryOps.h: In instantiation of const Eigen::CwiseBinaryOp<Eigen::internal::scalar_min_op<typename Eigen::internal::traits<T>::Scalar>, const Derived, const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<typename Eigen::internal::traits<T>::Scalar>, Derived> > Eigen::MatrixBase<Derived>::cwiseMin(const Scalar&) const [with Derived = Eigen::CwiseBinaryOp<Eigen::internal::scalar_max_op<double>, const Eigen::Matrix<double, -1, 1>, const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<double>, Eigen::Matrix<double, -1, 1> > >; typename Eigen::internal::traits<T>::Scalar = double; Eigen::MatrixBase<Derived>::Scalar = double]:
catkin_ws/build/gtsam_catkin/gtsam_src-prefix/src/gtsam_src/gtsam/nonlinear/LevenbergMarquardtOptimizer.cpp:283:71:   required from here
/usr/include/eigen3/Eigen/src/Core/../plugins/MatrixCwiseBinaryOps.h:86:72: error: could not convert Eigen::MatrixBase<Derived>::cwiseMin(const Eigen::MatrixBase<OtherDerived>&) const [with OtherDerived = Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<double>, Eigen::Matrix<double, -1, 1> >; Derived = Eigen::CwiseBinaryOp<Eigen::internal::scalar_max_op<double>, const Eigen::Matrix<double, -1, 1>, const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<double>, Eigen::Matrix<double, -1, 1> > >; typename Eigen::internal::traits<T>::Scalar = double]((*(const Eigen::MatrixBase<Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<double>, Eigen::Matrix<double, -1, 1> > >*)(& Eigen::DenseBase<Derived>::Constant(Eigen::DenseBase<Derived>::Index, Eigen::DenseBase<Derived>::Index, const Scalar&) [with Derived = Eigen::Matrix<double, -1, 1>; Eigen::DenseBase<Derived>::ConstantReturnType = Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<double>, Eigen::Matrix<double, -1, 1> >; typename Eigen::internal::traits<T>::Scalar = double; Eigen::DenseBase<Derived>::Index = long int; Eigen::DenseBase<Derived>::Scalar = double](((const Eigen::EigenBase<Eigen::CwiseBinaryOp<Eigen::internal::scalar_max_op<double>, const Eigen::Matrix<double, -1, 1>, const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<double>, Eigen::Matrix<double, -1, 1> > > >*)this)->Eigen::EigenBase<Derived>::cols<Eigen::CwiseBinaryOp<Eigen::internal::scalar_max_op<double>, const Eigen::Matrix<double, -1, 1>, const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<double>, Eigen::Matrix<double, -1, 1> > > >(), (* & other))))) from const Eigen::CwiseBinaryOp<Eigen::internal::scalar_min_op<double>, const Eigen::CwiseBinaryOp<Eigen::internal::scalar_max_op<double>, const Eigen::Matrix<double, -1, 1>, const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<double>, Eigen::Matrix<double, -1, 1> > >, const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<double>, Eigen::Matrix<double, -1, 1> > > to const Eigen::CwiseBinaryOp<Eigen::internal::scalar_min_op<double>, const Eigen::CwiseBinaryOp<Eigen::internal::scalar_max_op<double>, const Eigen::Matrix<double, -1, 1>, const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<double>, Eigen::Matrix<double, -1, 1> > >, const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<double>, Eigen::CwiseBinaryOp<Eigen::internal::scalar_max_op<double>, const Eigen::Matrix<double, -1, 1>, const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<double>, Eigen::Matrix<double, -1, 1> > > > >
   return cwiseMin(Derived::PlainObject::Constant(rows(), cols(), other));
                                                                        ^
/usr/include/eigen3/Eigen/src/Core/../plugins/MatrixCwiseBinaryOps.h: In member function const Eigen::CwiseBinaryOp<Eigen::internal::scalar_min_op<typename Eigen::internal::traits<T>::Scalar>, const Derived, const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<typename Eigen::internal::traits<T>::Scalar>, Derived> > Eigen::MatrixBase<Derived>::cwiseMin(const Scalar&) const [with Derived = Eigen::CwiseBinaryOp<Eigen::internal::scalar_max_op<double>, const Eigen::Matrix<double, -1, 1>, const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<double>, Eigen::Matrix<double, -1, 1> > >; typename Eigen::internal::traits<T>::Scalar = double; Eigen::MatrixBase<Derived>::Scalar = double]:
/usr/include/eigen3/Eigen/src/Core/../plugins/MatrixCwiseBinaryOps.h:87:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make[5]: *** [gtsam/CMakeFiles/gtsam.dir/nonlinear/LevenbergMarquardtOptimizer.cpp.o] Error 1
make[4]: *** [gtsam/CMakeFiles/gtsam.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [gtsam_src-prefix/src/gtsam_src-stamp/gtsam_src-build] Error 2
make[1]: *** [CMakeFiles/gtsam_src.dir/all] Error 2
make: *** [all] Error 2
[gtsam_catkin] <== build/gtsam_catkin/build_env.sh /usr/bin/make -j8 -l8' failed with return code '2'
                                                                                                                                                                                                                                      
[build] There were errors:                                                                                                                                                                                                           

    Failed to build package 'gtsam_catkin' because the following command:

        # Command run in directory: build/gtsam_catkin
        build/gtsam_catkin/build_env.sh /usr/bin/make -j8 -l8

    Exited with return code: 2 
[build] Runtime: 7.9 seconds 
```

```
$ dpkg -p libeigen3-dev
Package: libeigen3-dev
Priority: extra
Section: libdevel
Installed-Size: 3729
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: all
Source: eigen3
Version: 3.2.0-8
Provides: libeigen2-dev
Depends: pkg-config
Suggests: libeigen3-doc, libmrpt-dev
Size: 494158
Description: lightweight C++ template library for linear algebra
 Eigen 3 is a lightweight C++ template library for vector and matrix math,
 a.k.a. linear algebra.
 .
 Unlike most other linear algebra libraries, Eigen 3 focuses on the simple
 mathematical needs of applications: games and other OpenGL apps, spreadsheets
 and other office apps, etc. Eigen 3 is dedicated to providing optimal speed
 with GCC. A lot of improvements since 2-nd version of Eigen.
Original-Maintainer: Debian Science Maintainers <debian-science-maintainers@lists.alioth.debian.org>
Homepage: http://eigen.tuxfamily.org
```

**Comment by eggerk** [comment]
That's interesting. What version of eigen_catkin are you using? Because on 14.04, it should download Eigen 3.2.10 and not use the one provided by Ubuntu.

Can you also check the cmake log of eigen_catkin? On 14.04, I get something like
```
Suitable Eigen version not found. Minimum version: 3.2.10 Found version: 3.2.0
eigen_catkin is configured NOT to use system eigen
Using eigen_catkin's Eigen in /home/eggerk/catkin_ws/devel/include/eigen3
```

And on 16.04, it uses system-Eigen:
```
Suitable Eigen version found. Minimum version: 3.2.10 Found version: 3.2.92
eigen_catkin is configured to USE system eigen
Found and using system Eigen in /usr/include/eigen3
```

**Comment by hitimo** [comment]
Cleaned complete devel/build ws; now compiled successf.

**Pull request merged**
